// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynuqxchnmtjhqgjfwrcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InludXF4Y2hubXRqaHFnamZ3cmN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTEwMzEsImV4cCI6MjA2MDYyNzAzMX0.onc8U2asIWRrDhJyU7VxsJPDoj5ooOxvT1F71Wsf_JQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);